In [260]:
import pandas as pd
import numpy as np

In [261]:
dados = 'csv/base/hospedes.csv'
df = pd.read_csv(dados, sep=',')
df.head(10)

,id_hospede,nome,email,telefone,cidade_origem,estado,data_nascimento,genero
0,1,Carlos Pereira,carlos.pereira76@outlook.com,(24) 99935-2424,Rio de Janeiro,RJ,1969-03-24,M
1,2,Diego Alves,diego.alves29@outlook.com,(36) 99928-7873,Manaus,AM,1993-01-18,M
2,3,BRUNO RIBEIRO,bruno.ribeiro49@gmail.com,(54) 92674-2519,Belo Horizonte,MG,1972-03-07,M
3,4,Sandra Pereira,sandra.pereira71@yahoo.com,(26) 97201-2291,Fortaleza,CE,2001-08-18,F
4,5,Cristina Ferreira,carlossilva.semdominio,(48) 92307-4814,Recife,PE,1957-11-08,F
5,6,Mariana Carvalho,mariana.carvalho69@hotmail.com,(98) 92169-3803,Belo Horizonte,MG,1968-11-09,F
6,7,Amanda Dias,amanda.dias41@outlook.com,(18) 94752-1525,Rio de Janeiro,RJ,1998-06-27,Masculino
7,8,Paulo Martins,paulo.martins34@hotmail.com,11987654321,Rio de Janeiro,RJ,1996-08-13,M
8,9,cristina ribeiro,cristina.ribeiro12@gmail.com,(28) 99348-9085,Brasília,DF,1980-06-08,F
9,10,Bruno Ribeiro,bruno.ribeiro33@gmail.com,(87) 98668-9669,Brasília,DF,1959-07-13,M

In [262]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_hospede       402 non-null    int64
 1   nome             402 non-null    str
 2   email            402 non-null    str
 3   telefone         402 non-null    str
 4   cidade_origem    401 non-null    str
 5   estado           401 non-null    str
 6   data_nascimento  402 non-null    str
 7   genero           401 non-null    str
dtypes: int64(1), str(7)
memory usage: 25.3 KB

In [263]:
df.describe()

       id_hospede
count  402.000000
mean   199.875622
std    115.677488
min      1.000000
25%    100.000000
50%    199.500000
75%    299.750000
max    400.000000

In [264]:
#Dados sem resposta na coluna 'cidade_origem' preenchidos como "nulo"
df['cidade_origem'] = df['cidade_origem'].fillna('Nulo')
df['cidade_origem'].value_counts()

cidade_origem
Belo Horizonte    44
Brasília          43
Manaus            42
São Paulo         42
Porto Alegre      42
Curitiba          40
Rio de Janeiro    37
Fortaleza         37
Recife            37
Salvador          37
Nulo               1
Name: count, dtype: int64

In [265]:
#Dados sem resposta na coluna 'estado' preenchidos como "nulo"
df['estado'] = df['estado'].fillna('Nulo')
df['estado'].value_counts()

estado
MG                44
DF                43
AM                42
SP                41
RS                41
PR                40
CE                37
PE                37
BA                37
RJ                36
rio de janeiro     1
Nulo               1
Sp                 1
RRJ                1
Name: count, dtype: int64

In [266]:
#Dados sem resposta na coluna 'genero' preenchidos como "nulo"
df['genero'] = df['genero'].fillna('Nulo')
df['genero'].value_counts()

genero
F            200
M            199
Masculino      1
fem            1
Nulo           1
Name: count, dtype: int64

In [ ]:
df['genero'] = df['genero'].str.upper().value_counts()
df['genero'] = df['genero'].replace('MASCULINO', 'M')
df['genero']

In [133]:
#Exclusão de dados duplicados na base
df = df.drop_duplicates()

In [134]:
# Padronização do genero para M e F, convertendo todas as letras para caixa alta com upper() e substituindo as palavras necessárias para M ou F
df['genero'] = df['genero'].str.upper().replace('MASCULINO', 'M').replace('FEM', 'F')
df['genero'].value_counts()

genero
F    201
M    198
Name: count, dtype: int64

In [135]:
#Padronização do nome com caixa inconsistente 
df['nome'] =df['nome'].str.strip().str.title()
df['nome'].head()

0       Carlos Pereira
1          Diego Alves
2        Bruno Ribeiro
3       Sandra Pereira
4    Cristina Ferreira
Name: nome, dtype: str

In [136]:
#Preenchimento de emails inválidos como 'Nulo'
df['email'] = df['email'].isnull().sum() 
df['email'].value_counts()

email
0    400
Name: count, dtype: int64

In [ ]:
#Correção de telefones com formatos mistos 
df['telefone']

df['telefone']

0      24999352424
1      36999287873
2      54926742519
3      26972012291
4      48923074814
          ...
397    38954083994
398    42968333555
399    90961679066
400    14950514266
401    78928622041
Name: telefone, Length: 402, dtype: str

In [ ]:
# Preenchimento de dados nulos por dados de 'Não informado'
df['cidade_origem'] = df['cidade_origem'].fillna('Não informado')
df['estado'] = df['estado'].fillna('NI')
df['genero'] = df['genero'].fillna('N')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 402 entries, 0 to 401
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_hospede       402 non-null    int64
 1   nome             402 non-null    str
 2   email            402 non-null    str
 3   telefone         402 non-null    str
 4   cidade_origem    402 non-null    str
 5   estado           402 non-null    str
 6   data_nascimento  402 non-null    str
 7   genero           402 non-null    str
dtypes: int64(1), str(7)
memory usage: 25.3 KB